feature(canel-order): add a cancel order button
andela/gryffindor-rc pull request #14
Opened 2017-10-05 13:00 UTC by Charpell

### What does this PR do
Add a cancel order button

### Description of Task to be completed?
Gives Buyer option to cancel order after order has been made

### What are the relevant pivotal tracker stories?
As a registered user, when i make an order i should see a cancel order button. When i click on it, I should see a text field to add comments on why I want to cancel my order before submitting.
#151297875

### Screenshots 
<img width="885" alt="screen shot 2017-10-02 at 8 18 11 am" src="https://user-images.githubusercontent.com/21138774/31228434-73d53d84-a9d5-11e7-8307-0505f7fd64a9.png">

2017-10-05 18:01 UTC, emmyakin requested changes

2017-10-05 18:01 UTC, emmyakin commented on client/modules/accounts/templates/dropdown/dropdown.html
> +      <span id="logged-in-display-name" class="userName"> {{displayName}}<b class="caret"></b></span>
class names should be `all lowercase, or hyphenated`

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/list/ordersList.html
> +    <div class="panel-footer">
fix indentation between line 99-102

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/list/ordersList.js
> +    } else if (this.workflow.status === "canceled") {
**Code quality - nitpick**
remove `else` keyword here
why?  since we are explicitly calling return in `if` block, no need to use else

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/list/summary.js
> +    const currentData = Template.currentData();
is it possible to remove the two lines and just have
`this.state.set("order", Template.currentData().order)`

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/list/summary.js
> +    const order = state.get("order");
same thing as above here
unless `state` is going to be used several times, just assign values directly
What is the purpose of the variables here? they are not used anywhere

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/orders.html
> +            <span class="count" id="{{name}}">{{count}}</span>
what is the reason for setting `id={{name}}`?

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.js
> +  } else if (comment.length === 0) {
likewise remove `else` keyword

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.js
> +    const order = currentData.order;
`const order = Template.currentData().order;`

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.js
> +    return true;
I think you should return empty object here `{}`
Why?  See code where `validateComment` is used below

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.js
> +    if (validatedComment !== true) {
delete this line you should not compare values to Boolean, rather do this
`if (! validatedComment)` or `if (!$.isEmptyObject(errors))`

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.js
> +        errors: errors
with es6, you can do `{ errors }`

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.js
> +    if ($.isEmptyObject(errors) === false) {
see code above to refactor this

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.js
> +    const validatedComment = validateComment(comment);
if you return empty {} above
```
const message = validateComment(comment);
if (message.error) {
  return templateInstance.formMessages.set({
       errors: { comment: message }
   });
}
```

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.js
> +    const order = state.get("order");
is order used anywhere?

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.html
> +        <div class="form-group {{hasError messages.errors.comment}}">
I think `{{hasError messages.errors}}` is sufficient, same below
Why? - if there are no errors messages.errors would be undefined
This simplifies your hasError helper below

Maybe also rename helper to getErrorClass, cause that is basically what it does

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.js
> +    if (error !== true && typeof error !== "undefined") {
use ternary operator here
```
hasError(error) {
  return error ? "has-error has-feedback" : '';
}

2017-10-05 18:01 UTC, emmyakin commented on imports/plugins/core/orders/client/templates/workflow/workflow.html
> +          {{> coreOrderCancelOrder order=.}}
can you please explain "order=."? I have no idea what it means

2017-10-05 18:01 UTC, emmyakin commented on tests/acceptance-tests/config/user-data.yml
> +admin_user: Admin
Why change these values and where are the new ones from?

2017-10-07 15:13 UTC, Charpell commented on imports/plugins/core/orders/client/templates/workflow/cancelOrder.js
> +    const order = state.get("order");
Yes. order is used on line 96

2017-10-09 13:00 UTC, emmyakin approved these changes
Implement text comments in next ticket

2017-10-09 13:00 UTC, emmyakin commented on server/methods/core/orders.js
> +      "new": "Your Order has been successfully received and is been processed. Thanks.",
Your order has been successfully received and is being processed. Thanks.
Your order is on the way and will soon be delivered.
Your order has been delivered, Thanks.

2017-10-09 13:01 UTC, merged